# Generated by Django 5.2.5 on 2025-09-04 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('HIJAB', 'Hijab'), ('SHOES', 'Shoes'), ('OTHER', 'Other')], max_length=50)),
                ('subcategory', models.CharField(blank=True, choices=[('FLATS', 'Flats'), ('SANDALS', 'Sandals'), ('SNEAKERS', 'Sneakers'), ('BOOTS', 'Boots'), ('HEELS', 'Heels')], max_length=50, null=True)),
                ('colour', models.CharField(max_length=50)),
                ('fabric_type', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
