# Generated by Django 5.2.5 on 2025-09-06 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitDeclutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_worn', models.DateTimeField(blank=True, null=True)),
                ('wear_count', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('DONATE', 'Donate'), ('SELL', 'Sell'), ('DISPOSE', 'Dispose')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declutters', to='wardrobe.wardrobeitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declutters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
