# Generated by Django 5.2.5 on 2025-09-06 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occasion', models.CharField(blank=True, max_length=200, null=True)),
                ('items', models.ManyToManyField(related_name='planners', to='wardrobe.wardrobeitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_planners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
